services:
  smarlens:
    image: smarlens:beta-full
    pull_policy: never
    container_name: smarlens
    ports:
      - "8765:8765"
    environment:
      HOST: 0.0.0.0
      PORT: 8765
      PFAM_DB: /opt/smarlens/db/Pfam/Pfam-A.hmm
    volumes:
      - ./db/Pfam:/opt/smarlens/db/Pfam
    restart: unless-stopped
